### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-ec9j9#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by narayanatgit** [comment]
### change done src->item->index.js line no 52
![2022-09-05 (1)](https://user-images.githubusercontent.com/76954320/188472342-2498a3ec-9a11-45a3-8944-fb5cef8be4c1.png)
